name: Full Pipeline

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: .
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Pytest
        run: pytest tests/

  train:
    runs-on: ubuntu-latest
    needs: test
    env:
      PYTHONPATH: .
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Training
        run: python src/train.py

      - name: Upload model artifact
        uses: actions/upload-artifact@v3
        with:
          name: model
          path: model_train.pkl

  inference:
    runs-on: ubuntu-latest
    needs: train
    env:
      PYTHONPATH: .
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Download model artifact
        uses: actions/download-artifact@v3
        with:
          name: model
          path: .

      - name: Run inference
        run: python src/inference.py
